// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://wpshwxydcokxgfnkesbo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Indwc2h3eHlkY29reGdmbmtlc2JvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgxMjcyMzQsImV4cCI6MjA2MzcwMzIzNH0.z4IDqzlKfUKc5r8qOiS_P-eElMHAAg3vvv9Mx0ndfGo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);